# Generated by Django 5.2.12 on 2026-09-29 20:03

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название целевого сервиса")),
                ("tag", models.CharField(max_length=10, unique=True, verbose_name="Тег")),
                ("short_url", models.URLField(blank=True, verbose_name="Короткая ссылка")),
                ("visits", models.PositiveIntegerField(default=0, verbose_name="Переходы")),
            ],
        ),
        migrations.CreateModel(
            name="Berries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
                ("index_value", models.PositiveIntegerField(unique=True, verbose_name="Номер с фронта")),
            ],
            options={
                "verbose_name": "ягоды",
                "verbose_name_plural": "ягоды",
                "ordering": ["index_value"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Decor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
                ("index_value", models.PositiveIntegerField(unique=True, verbose_name="Номер с фронта")),
            ],
            options={
                "verbose_name": "декор",
                "verbose_name_plural": "декор",
                "ordering": ["index_value"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
                ("index_value", models.PositiveIntegerField(unique=True, verbose_name="Номер с фронта")),
            ],
            options={
                "verbose_name": "форма",
                "verbose_name_plural": "формы",
                "ordering": ["index_value"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
                ("index_value", models.PositiveIntegerField(unique=True, verbose_name="Номер с фронта")),
            ],
            options={
                "verbose_name": "количество уровней",
                "verbose_name_plural": "количества уровней",
                "ordering": ["index_value"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Промокод")),
                ("discount_percent", models.PositiveIntegerField(verbose_name="Скидка %")),
                ("valid_from", models.DateTimeField(verbose_name="Действует с")),
                ("valid_until", models.DateTimeField(verbose_name="Действует до")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("max_uses", models.PositiveIntegerField(default=1, verbose_name="Максимум использований")),
                ("used_count", models.PositiveIntegerField(default=0, verbose_name="Количество использований")),
            ],
        ),
        migrations.CreateModel(
            name="Topping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
                ("index_value", models.PositiveIntegerField(unique=True, verbose_name="Номер с фронта")),
            ],
            options={
                "verbose_name": "топпинг",
                "verbose_name_plural": "топпинги",
                "ordering": ["index_value"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("username", models.CharField(max_length=20, unique=True, verbose_name="Номер телефона")),
                ("first_name", models.CharField(blank=True, max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(blank=True, max_length=50, verbose_name="Почта")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_name", models.CharField(max_length=50, verbose_name="Имя клиента")),
                ("phone_number", models.CharField(max_length=20, verbose_name="Номер телефона")),
                ("email", models.EmailField(max_length=50, verbose_name="Почта")),
                ("address", models.CharField(max_length=100, verbose_name="Адрес")),
                ("delivery_date", models.DateField(verbose_name="Дата доставки")),
                ("delivery_time", models.TimeField(verbose_name="Время доставки")),
                ("delivery_comment", models.TextField(blank=True, verbose_name="Комментарий курьеру")),
                ("inscription", models.CharField(blank=True, max_length=50, verbose_name="Надпись")),
                ("cake_comment", models.TextField(blank=True, verbose_name="Комментарий к заказу")),
                ("price", models.PositiveIntegerField(verbose_name="Общая цена")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "berry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cakes.berries",
                        verbose_name="Ягоды",
                    ),
                ),
                (
                    "decor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cakes.decor",
                        verbose_name="Декор",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cakes.form", verbose_name="Форма"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cakes.level", verbose_name="Уровни"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "topping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cakes.topping", verbose_name="Топпинг"
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
    ]
