# Generated by Django 5.2.12 on 2026-10-01 10:28

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cake",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
            ],
            options={
                "verbose_name": "готовый торт",
                "verbose_name_plural": "готовые торты",
            },
        ),
        migrations.RenameModel(
            old_name="Form",
            new_name="CakeForm",
        ),
        migrations.DeleteModel(
            name="PromoCode",
        ),
        migrations.RemoveField(
            model_name="order",
            name="form",
        ),
        migrations.AddField(
            model_name="order",
            name="cake_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cakes.cakeform",
                verbose_name="Форма",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Не обработан"),
                    ("PREPARING", "Готовится"),
                    ("DELIVERING", "У курьера"),
                    ("COMPLETED", "Доставлен"),
                    ("CANCELLED", "Отменён"),
                ],
                db_index=True,
                default="CREATED",
                max_length=15,
                verbose_name="статус",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="utm",
            field=models.CharField(blank=True, max_length=50, verbose_name="Рекламная метка"),
        ),
        migrations.AddField(
            model_name="user",
            name="pd_consent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Согласие на обработку ПД"),
        ),
        migrations.AlterField(
            model_name="order",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cakes.level",
                verbose_name="Уровни",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=20, region="RU", verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="topping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cakes.topping",
                verbose_name="Топпинг",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=20, region="RU", unique=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cakes.cake",
                verbose_name="Готовый торт",
            ),
        ),
    ]
