# Generated by Django 5.2.12 on 2026-10-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0002_cake_rename_form_cakeform_delete_promocode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adlink",
            name="short_url",
        ),
    ]
