# Generated by Django 5.2.12 on 2026-10-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0003_remove_adlink_short_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="cake",
            name="image",
            field=models.ImageField(blank=True, upload_to="cakes/", verbose_name="Фото"),
        ),
    ]
