# Generated by Django 5.2.12 on 2026-10-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0004_cake_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cake",
            options={"ordering": ["id"], "verbose_name": "готовый торт", "verbose_name_plural": "готовые торты"},
        ),
    ]
