name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: black
        run: black --check .

      - name: isort
        if: success() || failure()
        run: isort --check-only --diff .

      - name: flake8
        if: success() || failure()
        run: flake8 .